server:
  port: 0

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.instance.id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:30000/eureka

spring:
  application:
    name: memo-service
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/chinchinne
    driver-class-name: org.mariadb.jdbc.Driver
    username: backend
    password: backend
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true

logging:
  level:
    org:
      hibernate:
        sql: debug
        type:
          descriptor:
            sql: trace
    root: info
